# This configuration is only for dependency services for testing and local development.
# You can start this with make containers_up command.
#
# To build a container with the application itself use make docker_up command.
#
version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  s3:
    image: minio/minio
    volumes:
      - s3:/data
    environment:
      MINIO_CONSOLE_ADDRESS: ":9001"
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports:
      - '9000:9000'
      - '9001:9001'

  minio-setup:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: /bin/sh -c "mc config host add myminio http://s3:9000 minio minio123 && mc mb myminio/exam-depository-bucket"
volumes:
  db:
    driver: local
  s3:
    driver: local
